// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Entity
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject entityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Entity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		LocalNoDefault("LocalNoDefault"),
		LocalNoDefaultZone("LocalNoDefaultZone"),
		UTCNoDefault("UTCNoDefault"),
		UTCNoDefaultZone("UTCNoDefaultZone"),
		LocalDefaultNow("LocalDefaultNow"),
		LocalDefaultNowZone("LocalDefaultNowZone"),
		UTCDefaultNow("UTCDefaultNow"),
		UTCDefaultNowZone("UTCDefaultNowZone");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Entity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Entity"));
	}

	protected Entity(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject entityMendixObject)
	{
		if (entityMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Entity", entityMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Entity");

		this.entityMendixObject = entityMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Entity.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Entity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Entity.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Entity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Entity(context, mendixObject);
	}

	public static myfirstmodule.proxies.Entity load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Entity.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Entity> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Entity> result = new java.util.ArrayList<myfirstmodule.proxies.Entity>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Entity" + xpathConstraint))
			result.add(myfirstmodule.proxies.Entity.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of LocalNoDefault
	 */
	public final java.util.Date getLocalNoDefault()
	{
		return getLocalNoDefault(getContext());
	}

	/**
	 * @param context
	 * @return value of LocalNoDefault
	 */
	public final java.util.Date getLocalNoDefault(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LocalNoDefault.toString());
	}

	/**
	 * Set value of LocalNoDefault
	 * @param localnodefault
	 */
	public final void setLocalNoDefault(java.util.Date localnodefault)
	{
		setLocalNoDefault(getContext(), localnodefault);
	}

	/**
	 * Set value of LocalNoDefault
	 * @param context
	 * @param localnodefault
	 */
	public final void setLocalNoDefault(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date localnodefault)
	{
		getMendixObject().setValue(context, MemberNames.LocalNoDefault.toString(), localnodefault);
	}

	/**
	 * @return value of LocalNoDefaultZone
	 */
	public final java.lang.String getLocalNoDefaultZone()
	{
		return getLocalNoDefaultZone(getContext());
	}

	/**
	 * @param context
	 * @return value of LocalNoDefaultZone
	 */
	public final java.lang.String getLocalNoDefaultZone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LocalNoDefaultZone.toString());
	}

	/**
	 * Set value of LocalNoDefaultZone
	 * @param localnodefaultzone
	 */
	public final void setLocalNoDefaultZone(java.lang.String localnodefaultzone)
	{
		setLocalNoDefaultZone(getContext(), localnodefaultzone);
	}

	/**
	 * Set value of LocalNoDefaultZone
	 * @param context
	 * @param localnodefaultzone
	 */
	public final void setLocalNoDefaultZone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String localnodefaultzone)
	{
		getMendixObject().setValue(context, MemberNames.LocalNoDefaultZone.toString(), localnodefaultzone);
	}

	/**
	 * @return value of UTCNoDefault
	 */
	public final java.util.Date getUTCNoDefault()
	{
		return getUTCNoDefault(getContext());
	}

	/**
	 * @param context
	 * @return value of UTCNoDefault
	 */
	public final java.util.Date getUTCNoDefault(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.UTCNoDefault.toString());
	}

	/**
	 * Set value of UTCNoDefault
	 * @param utcnodefault
	 */
	public final void setUTCNoDefault(java.util.Date utcnodefault)
	{
		setUTCNoDefault(getContext(), utcnodefault);
	}

	/**
	 * Set value of UTCNoDefault
	 * @param context
	 * @param utcnodefault
	 */
	public final void setUTCNoDefault(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date utcnodefault)
	{
		getMendixObject().setValue(context, MemberNames.UTCNoDefault.toString(), utcnodefault);
	}

	/**
	 * @return value of UTCNoDefaultZone
	 */
	public final java.lang.String getUTCNoDefaultZone()
	{
		return getUTCNoDefaultZone(getContext());
	}

	/**
	 * @param context
	 * @return value of UTCNoDefaultZone
	 */
	public final java.lang.String getUTCNoDefaultZone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UTCNoDefaultZone.toString());
	}

	/**
	 * Set value of UTCNoDefaultZone
	 * @param utcnodefaultzone
	 */
	public final void setUTCNoDefaultZone(java.lang.String utcnodefaultzone)
	{
		setUTCNoDefaultZone(getContext(), utcnodefaultzone);
	}

	/**
	 * Set value of UTCNoDefaultZone
	 * @param context
	 * @param utcnodefaultzone
	 */
	public final void setUTCNoDefaultZone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String utcnodefaultzone)
	{
		getMendixObject().setValue(context, MemberNames.UTCNoDefaultZone.toString(), utcnodefaultzone);
	}

	/**
	 * @return value of LocalDefaultNow
	 */
	public final java.util.Date getLocalDefaultNow()
	{
		return getLocalDefaultNow(getContext());
	}

	/**
	 * @param context
	 * @return value of LocalDefaultNow
	 */
	public final java.util.Date getLocalDefaultNow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LocalDefaultNow.toString());
	}

	/**
	 * Set value of LocalDefaultNow
	 * @param localdefaultnow
	 */
	public final void setLocalDefaultNow(java.util.Date localdefaultnow)
	{
		setLocalDefaultNow(getContext(), localdefaultnow);
	}

	/**
	 * Set value of LocalDefaultNow
	 * @param context
	 * @param localdefaultnow
	 */
	public final void setLocalDefaultNow(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date localdefaultnow)
	{
		getMendixObject().setValue(context, MemberNames.LocalDefaultNow.toString(), localdefaultnow);
	}

	/**
	 * @return value of LocalDefaultNowZone
	 */
	public final java.lang.String getLocalDefaultNowZone()
	{
		return getLocalDefaultNowZone(getContext());
	}

	/**
	 * @param context
	 * @return value of LocalDefaultNowZone
	 */
	public final java.lang.String getLocalDefaultNowZone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LocalDefaultNowZone.toString());
	}

	/**
	 * Set value of LocalDefaultNowZone
	 * @param localdefaultnowzone
	 */
	public final void setLocalDefaultNowZone(java.lang.String localdefaultnowzone)
	{
		setLocalDefaultNowZone(getContext(), localdefaultnowzone);
	}

	/**
	 * Set value of LocalDefaultNowZone
	 * @param context
	 * @param localdefaultnowzone
	 */
	public final void setLocalDefaultNowZone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String localdefaultnowzone)
	{
		getMendixObject().setValue(context, MemberNames.LocalDefaultNowZone.toString(), localdefaultnowzone);
	}

	/**
	 * @return value of UTCDefaultNow
	 */
	public final java.util.Date getUTCDefaultNow()
	{
		return getUTCDefaultNow(getContext());
	}

	/**
	 * @param context
	 * @return value of UTCDefaultNow
	 */
	public final java.util.Date getUTCDefaultNow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.UTCDefaultNow.toString());
	}

	/**
	 * Set value of UTCDefaultNow
	 * @param utcdefaultnow
	 */
	public final void setUTCDefaultNow(java.util.Date utcdefaultnow)
	{
		setUTCDefaultNow(getContext(), utcdefaultnow);
	}

	/**
	 * Set value of UTCDefaultNow
	 * @param context
	 * @param utcdefaultnow
	 */
	public final void setUTCDefaultNow(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date utcdefaultnow)
	{
		getMendixObject().setValue(context, MemberNames.UTCDefaultNow.toString(), utcdefaultnow);
	}

	/**
	 * @return value of UTCDefaultNowZone
	 */
	public final java.lang.String getUTCDefaultNowZone()
	{
		return getUTCDefaultNowZone(getContext());
	}

	/**
	 * @param context
	 * @return value of UTCDefaultNowZone
	 */
	public final java.lang.String getUTCDefaultNowZone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UTCDefaultNowZone.toString());
	}

	/**
	 * Set value of UTCDefaultNowZone
	 * @param utcdefaultnowzone
	 */
	public final void setUTCDefaultNowZone(java.lang.String utcdefaultnowzone)
	{
		setUTCDefaultNowZone(getContext(), utcdefaultnowzone);
	}

	/**
	 * Set value of UTCDefaultNowZone
	 * @param context
	 * @param utcdefaultnowzone
	 */
	public final void setUTCDefaultNowZone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String utcdefaultnowzone)
	{
		getMendixObject().setValue(context, MemberNames.UTCDefaultNowZone.toString(), utcdefaultnowzone);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return entityMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Entity that = (myfirstmodule.proxies.Entity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Entity";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
